name: Aqua
on:
  push:
    branches:
      - main

env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: "stanhoe"
      DOCKER_REPOSITORY: "graphql"
      IMAGE_TAG: ${{ github.sha }}
      BUILD_NUMBER: ${{ github.run_id }}
      BUILD_NAME: ${{ github.repository }}
      AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
      AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
      AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
      AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry

jobs:
  code-scanning:
    name: Aqua Code Scanner
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Aqua Pipeline Enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        env:
          CSPM_URL: https://asia-1.api.cloudsploit.com
          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}

      - name: Run Aqua Code Scanner
        run: |
          docker pull aquasec/aqua-scanner
          docker run \
            -v ${{ github.workspace }}:/scanning \
            -e AQUA_KEY=${{ secrets.AQUA_KEY }} \
            -e AQUA_SECRET=${{ secrets.AQUA_SECRET }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e AQUA_URL=https://api.asia-1.supply-chain.cloud.aquasec.com \
            -e CSPM_URL=https://asia-1.api.cloudsploit.com \
            -e TRIVY_RUN_AS_PLUGIN='aqua' \
            -e INPUT_WORKING_DIRECTORY=/scanning \
            aquasec/aqua-scanner \
            trivy -d fs --scanners config,vuln,secret --sast --reachability . --format template -o aqua-code-scanner.html
        
      - name: Upload Aqua Code Scanner Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aqua-artifact
          path: aqua-code-scanner.*
          
      - name: Manifest Generation (SBOM)
        run: |
          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum --check; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://asia-1.api.cloudsploit.com \
            --artifact-path "${{ github.workspace }}"

  image-scanning:
    name: Aqua Image Scanner
    needs: code-scanning
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Aqua Pipeline Enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        env:
          CSPM_URL: https://asia-1.api.cloudsploit.com
          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}
        
      - name: Build Image Locally
        run: |
          docker build -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" .
          
      - name: Run Aqua Image Scanner
        run: |
          docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
          docker pull registry.aquasec.com/scanner:2406.10.19 
          docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2404.30.6 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --local $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG --register-compliant --registry "Docker Hub" --htmlfile /tmp/aqua-image-scanner.html --jsonfile /tmp/aqua-image-scanner.json > /dev/null

      - name: Upload Aqua Image Scanner Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aqua-artifact
          path: aqua-image-scanner.*
         
      - name: Manifest Generation (SBOM)
        run: |
          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum --check; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://asia-1.api.cloudsploit.com \
            --artifact-path "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
            
      - name: Tag and push image to Docker Hub (+latest)
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
